### ISSUE TITLE
give RelTableModel named arguments

### ISSUE THREAD

**Issue by klin333** [patzaw/ReDaMoR#2]
Hi,

First of all this package is awesome! Much better than all alternatives I've tried. Hats off to you.

One potential improvement could be to change RelTableModel() to take in named arguments, as opposed to one named list. I understand it's easier to just take in a named list when used in the shiny app you have. However, I use this package without the shiny app, where i directly call RelTableModel() in R code. In this use case, it makes much more sense for the function to take named arguments eg tableName, fields, primaryKey etc.  For the shiny use case, can always do.call

thoughts?

**Comment by patzaw** [comment]
Hi

Thanks for your feedback.

You're absolutely right. It makes much more sense to have named arguments instead of one list. It's a little bit embarrassing because I can't remember why I've implemented it this way originally :-).

I'll update the function accordingly. I'll probably keep the "l" parameter for reverse-compatibility reason (at least for some time with a warning message about its deprecation).
